"""供应商无关的 Agent 循环契约。"""

from ycode.agent.contracts import (
    AgentLoopOptions,
    AgentMode,
    AgentNotificationSource,
    AgentRequestSnapshot,
    AgentTermination,
    AgentToolPolicy,
    AgentToolScope,
    AgentTurn,
    AgentTurnResult,
    AgentTurnStream,
    ConversationRunner,
    OwnedTurnController,
    ToolPolicyDecision,
    TurnMessage,
)
from ycode.agent.events import (
    AgentCancelledEvent,
    AgentErrorEvent,
    AgentEvent,
    AgentLimitReachedEvent,
    AgentTextDelta,
    AgentThinkingDelta,
    ContextCompactedEvent,
    ContextCompactionFailedEvent,
    ContextCompactionNotNeededEvent,
    FinalResponseEvent,
    HookNoticeEvent,
    McpStatusEvent,
    ModeChangedEvent,
    PermissionGrantsClearedEvent,
    PermissionModeChangedEvent,
    SessionRestoredEvent,
    ToolApprovalRequested,
    ToolExecutionCancelled,
    ToolExecutionCompleted,
    ToolExecutionStarted,
    UserMessageEvent,
)
from ycode.agent.loop import AgentLoop
from ycode.agent.plain import PlainChatRunner

__all__ = [
    "AgentCancelledEvent",
    "AgentErrorEvent",
    "AgentEvent",
    "AgentLimitReachedEvent",
    "AgentLoop",
    "AgentLoopOptions",
    "AgentMode",
    "AgentNotificationSource",
    "AgentRequestSnapshot",
    "AgentTermination",
    "AgentTextDelta",
    "AgentThinkingDelta",
    "AgentTurn",
    "AgentTurnResult",
    "AgentTurnStream",
    "AgentToolPolicy",
    "AgentToolScope",
    "ConversationRunner",
    "ContextCompactedEvent",
    "ContextCompactionFailedEvent",
    "ContextCompactionNotNeededEvent",
    "FinalResponseEvent",
    "HookNoticeEvent",
    "ModeChangedEvent",
    "McpStatusEvent",
    "PermissionGrantsClearedEvent",
    "PermissionModeChangedEvent",
    "OwnedTurnController",
    "PlainChatRunner",
    "SessionRestoredEvent",
    "ToolExecutionCancelled",
    "ToolApprovalRequested",
    "ToolExecutionCompleted",
    "ToolExecutionStarted",
    "ToolPolicyDecision",
    "TurnMessage",
    "UserMessageEvent",
]
